### PR TITLE
add example select game dialog with two games

### PR DESCRIPTION
**Pull request by raisjn**
loopy doesn't really work, but just using it for testing

### CODE REVIEW

**Comment by raisjn** [comment]
as i added the Pager stuff, i realized it isn't as friendly. i added a "selected" signal to this pager subclass, but would like to make an easier Pager to use in general in rmkit. 

on that note: i noticed there's a few TODOs and upgrades to rmkit that you mention in the code: is there stuff i can upstream / add that you want? i like the vertical centering on buttons, for example.

**Comment by raisjn** [comment]
misc problems:

* if dismissing pager, game doesn't refresh - the canvas (or whatever is container for the game) should re-render the game when render() is called. maybe it needs to be set to dirty?
* when starting new game of loops then going back to lightup, there is weird redrawing issue - need to fully clear screen before swapping games

**Comment by mrichards42** [comment]
Awesome! I'll take a look at how this works later today. I was initially thinking about have an intro scene that would double as the picker (there's an android version that works like that), but I haven't thought it all through yet. I noticed that Pager is a subclass of Dialog (which I assume is meant to be used as an overlay?) I could see Pager being useful as a standalone Widget as well, but I haven't even gotten that far so I might not understand how it works yet :)

> on that note: i noticed there's a few TODOs and upgrades to rmkit that you mention in the code: is there stuff i can upstream / add that you want? i like the vertical centering on buttons, for example.

Oh yeah, mostly just keeping notes as I run into things. I was planning on sending over some PRs, but I could start w/ issues if that would be faster/easier for you. So far the biggest thing is vertically centering text. I'm doing that with OutlineButton and the puzzles api needs to be able to draw centered text as well (e.g. lightup centers the text in squares). I'm not 100% sure my implementation of the latter ([here](https://github.com/mrichards42/remarkable_puzzles/blob/878b0daf660895c94f10f19e23423f334dd04d52/src/main.cpp#L106-L116)) is correct -- in fact it looks like the text is a little lower than it should be.

**Comment by mrichards42** [comment]
> if dismissing pager, game doesn't refresh - the canvas (or whatever is container for the game) should re-render the game when render() is called. maybe it needs to be set to dirty?

That makes sense -- the puzzles api is supposed to keep track of the dirty region and call [draw_update()](https://github.com/mrichards42/remarkable_puzzles/blob/878b0daf660895c94f10f19e23423f334dd04d52/src/main.cpp#L254-L259) when it has a region to refresh, according to the [docs](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/devel/drawing.html#drawingapi-draw-update). I've assumed that drawing to the framebuffer is kind of expensive, but if it isn't `Canvas::render()` could just copy the full vfb each time.

**Comment by raisjn** [comment]
> Awesome! I'll take a look at how this works later today. I was initially thinking about have an intro scene that would double as the picker (there's an android version that works like that), but I haven't thought it all through yet. I noticed that Pager is a subclass of Dialog (which I assume is meant to be used as an overlay?) I could see Pager being useful as a standalone Widget as well, but I haven't even gotten that far so I might not understand how it works yet :)

yeah, IPager is only used as a modal overlay at the moment. i think making a new scene with the game selection makes more sense, though. the pager could be used for setting game params (i was reading docs and i think games support preset parameters with names or something similar?), but its also possible to make a dropdown (or dropup). 

i'll abandon this diff, since i like the intro scene better

**Comment by raisjn** [comment]
> That makes sense -- the puzzles api is supposed to keep track of the dirty region and call draw_update() when it has a region to refresh, according to the docs. I've assumed that drawing to the framebuffer is kind of expensive, but if it isn't Canvas::render() could just copy the full vfb each time.

the render() is called when a widget is marked as dirty. a widget is usually marked as dirty if ui::MainLoop::refresh() is called (marks all widgets dirty) or the widget is manually marked dirty. the canvas will not have render() called on it often (only when changing scenes and hiding ' showing overlays, i think), but can add a logging line and check.

**Pull request closed without merging**
